"""
为什么会抛出异常
最终会交给python的解释器执行
如果遇到一个错误会终止程序，输出错误信息
这个就是抛出异常
稳定，健壮的产品，不会时不时停止报告产品问题

"""
num=int(input("输入整数"))
#抛出异常是抛给程序员
#程序则不会停止
